spring:
  datasource:
    url: jdbc:mysql://localhost:3306/publicacoesonline?createDatabaseIfNotExist=true&serverTimeZone=UTC
    username: root
    password: f2;k
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml